FROM registry.gitlab.com/datadrivendiscovery/images/core:ubuntu-artful-python36-v2018.7.10

RUN mkdir -p /user_opt
RUN mkdir -p /output
RUN mkdir -p /input

ENV CODE /user_opt/dsbox
ENV TA2 $CODE/dsbox-ta2/python

RUN pip3 install --upgrade pip

RUN mkdir $CODE

RUN cd $CODE && pip3 install -e git+https://gitlab.com/datadrivendiscovery/sklearn-wrap@bf101e1e4b0565e03c2aaa80b5bdd8f0fda04bd7#egg=sklearn-wrap
RUN cd $CODE && pip3 install -e git+https://gitlab.com/datadrivendiscovery/common-primitives@ed9761b0983f19f1655c681c2f2b30a9e4f162ff#egg=common-primitives

RUN cd $CODE && pip3 install -e git+https://github.com/usc-isi-i2/dsbox-cleaning@13d534592f1f5cc4bd8c33f09463546ad342399d#egg=dsbox-datacleaning
RUN cd $CODE && pip3 install -e git+https://github.com/usc-isi-i2/dsbox-featurizer@59dacbd057bf16372fdf521117aa6d3e2af6cff9#egg=dsbox-featurizer
RUN cd $CODE && pip3 install -e git+https://github.com/brekelma/dsbox_corex@5507a14ac42157d433e34ecb6ccede5112bf20c1#egg=dsbox_corex

RUN cd $CODE \
&& git clone https://github.com/usc-isi-i2/dsbox-ta2.git \
&& cd dsbox-ta2 \
&& git checkout 27872658e3c554faef460a02665930954c910fc4


RUN \
sed -i.bak 's/env python/env python3/' \
$TA2/ta2-search \
$TA2/ta1-run-single-template \
$TA2/server/ta2-server.py \
$TA2/server/ta2-client.py

COPY startup.sh /user_opt
RUN chmod a+x /user_opt/startup.sh

ENTRYPOINT ["/user_opt/startup.sh"]
CMD []
