FROM registry.datadrivendiscovery.org/jpl/docker_images/complete:ubuntu-artful-python36-v2018.7.10



RUN mkdir -p /user_opt
RUN mkdir -p /output
RUN mkdir -p /input

ENV CODE /user_opt/dsbox
ENV TA2 $CODE/dsbox-ta2/python

# Install packages need by JHU primitives
RUN apt-get update && apt-get -y install r-base-core gfortran libblas-dev liblapack-dev libjpeg-dev
RUN wget http://ftp.us.debian.org/debian/pool/main/c/cdbs/cdbs_0.4.156_all.deb
RUN dpkg -i cdbs_0.4.156_all.deb
RUN apt-get install r-base
RUN apt-get install r-base-dev
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile


RUN pip3 install --upgrade pip

RUN mkdir $CODE

RUN cd $CODE && pip3 install -e git+https://gitlab.com/datadrivendiscovery/sklearn-wrap@9346c271559fd221dea4bc99c352ce10e518759c#egg=sklearn-wrap
RUN cd $CODE && pip3 install -e git+https://gitlab.com/datadrivendiscovery/common-primitives@ed9761b0983f19f1655c681c2f2b30a9e4f162ff#egg=common-primitives

RUN cd $CODE \
&& git clone https://github.com/usc-isi-i2/dsbox-ta2.git \
&& cd dsbox-ta2 \
&& git checkout cc7fa18d35cf2f270ef4948c0f620274de29ce4a

RUN cd $CODE && pip3 install -e git+https://github.com/usc-isi-i2/dsbox-cleaning@436e25b0ea52cf95b46cb9be27934c1ede8c76cf#egg=dsbox-datacleaning
RUN cd $CODE && pip3 install -e git+https://github.com/brekelma/dsbox_corex@5507a14ac42157d433e34ecb6ccede5112bf20c1#egg=dsbox_corex
RUN cd $CODE && pip3 install -e git+https://github.com/usc-isi-i2/dsbox-featurizer@516678427a7473c730c79a401184bfaecfe959f3#egg=dsbox-featurizer



RUN \
sed -i.bak 's/env python/env python3/' \
$TA2/ta2-search \
$TA2/ta1-run-single-template \
$TA2/server/ta2-server.py \
$TA2/server/ta2-client.py

COPY startup.sh /user_opt
RUN chmod a+x /user_opt/startup.sh

ENTRYPOINT ["/user_opt/startup.sh"]
CMD []
